### ISSUE TITLE
Check for changes in .docx source files and only convert modified files to save time

### ISSUE THREAD

**Issue by themorlan** [luc-ass/pdf-overlay#14]
Check for file changes with st_mtime and st_size and additionally with md5 hash (hashlib).

**Comment by luc-ass** [comment]
Great idea! Any ideas on where to save those hashes? Create dotfiles?

**Comment by luc-ass** [comment]
Typical structure as stated [here](https://docs.fileformat.com/misc/md5/#:~:text=check%20MD5%20Checksum%3F-,What%20is%20an%20MD5%20file%3F,with%20software%20such%20as%20md5sum.):
`some_file.ext`
`some_file.ext.md5`

**Comment by themorlan** [comment]
Or maybe a json file with filename (key): md5-hash (value) to remove the amount of files in the document folder
